# Generated by Django 3.2.7 on 2021-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklisthost',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
