# Generated by Django 3.2.7 on 2021-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0002_auto_20210910_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
