# Generated by Django 3.2.7 on 2021-09-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0004_otpenroll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPEnroll',
            new_name='OTTEnroll',
        ),
        migrations.RenameField(
            model_name='ottenroll',
            old_name='otp',
            new_name='ott',
        ),
        migrations.RenameField(
            model_name='ottenroll',
            old_name='otp_expires',
            new_name='ott_expires',
        ),
    ]
